<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Healtive.Application\Healtive.Application.csproj" />
    <ProjectReference Include="..\Healtive.Core\Healtive.Core.csproj" />
    <ProjectReference Include="..\Healtive.Infrastructure\Healtive.Infrastructure.csproj" />
    <ProjectReference Include="..\Healtive.Shared\Healtive.Shared.csproj" />
  </ItemGroup>

</Project>
