<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Authentication\**" />
    <Compile Remove="Email\**" />
    <Compile Remove="FileStorage\**" />
    <Compile Remove="Persistence\**" />
    <EmbeddedResource Remove="Authentication\**" />
    <EmbeddedResource Remove="Email\**" />
    <EmbeddedResource Remove="FileStorage\**" />
    <EmbeddedResource Remove="Persistence\**" />
    <None Remove="Authentication\**" />
    <None Remove="Email\**" />
    <None Remove="FileStorage\**" />
    <None Remove="Persistence\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.20.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.20.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Healtive.Application\Healtive.Application.csproj" />
    <ProjectReference Include="..\Healtive.Core\Healtive.Core.csproj" />
    <ProjectReference Include="..\Healtive.Shared\Healtive.Shared.csproj" />
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
